---
gitHubLogin: "k8s-infra-ci-robot"
gitHubToken: "/etc/github-token/token"
gitName: "Kubernetes Prow Robot"
gitEmail: "75457971+k8s-infra-ci-robot@users.noreply.github.com"
skipPullRequest: false
gitHubOrg: "kubernetes"
gitHubRepo: "k8s.io"
remoteName: "k8s.io"
upstreamURLBase: "https://raw.githubusercontent.com/kubernetes/k8s.io/main"
includedConfigPaths:
  - "kubernetes"
excludedConfigPaths:
  - "registry.k8s.io"
targetVersion: "latest"
prefixes:
  - name: "boskos"
    prefix: "gcr.io/k8s-staging-boskos/"
    repo: "https://github.com/kubernetes-sigs/boskos"
    summarise: false
    consistentImages: true
  - name: "ghproxy"
    prefix: "us-docker.pkg.dev/k8s-infra-prow/images/ghproxy"
    repo: "https://github.com/kubernetes-sigs/prow"
    summarise: false
  - name: "prow"
    prefix: "us-docker.pkg.dev/k8s-infra-prow/images/"
    repo: "https://github.com/kubernetes-sigs/prow"
    summarise: false
    consistentImages: true
