---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-infra-ibmcloud-iam
  namespace: test-pods
spec:
  refreshInterval: 60m
  secretStoreRef:
    name: secretstore-ibm-k8s
    kind: ClusterSecretStore
  target:
    name: k8s-infra-ibmcloud-iam
    creationPolicy: Owner
  data:
  - secretKey: key
    remoteRef:
      key: iam_credentials/c4c5e90a-408d-69de-38b2-0d56d58d29db
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-infra-ssh-key
  namespace: test-pods
spec:
  refreshInterval: 60m
  secretStoreRef:
    name: secretstore-ibm-k8s
    kind: ClusterSecretStore
  target:
    name: k8s-infra-ssh-key
    creationPolicy: Owner
  data:
  - secretKey: ssh-privatekey
    remoteRef:
      key: 72d8039f-6cfc-1bbf-ba8e-d85985b42ee0
