apiVersion: v1
kind: Secret
metadata:
  name: service-account
  namespace: test-pods
stringData:
  service-account.json: |
    {
      "universe_domain": "googleapis.com",
      "type": "external_account",
      "audience": "//iam.googleapis.com/projects/16065310909/locations/global/workloadIdentityPools/ibm-clusters/providers/ppc64le",
      "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
      "token_url": "https://sts.googleapis.com/v1/token",
      "credential_source": {
        "file": "/var/run/secrets/google-iam-token/serviceaccount/token",
        "format": {
          "type": "text"
        }
      }
    }
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-infra-ibmcloud-iam
  namespace: test-pods
spec:
  refreshInterval: 60m
  secretStoreRef:
    name: secretstore-ibm-k8s
    kind: ClusterSecretStore
  target:
    name: k8s-infra-ibmcloud-iam
    creationPolicy: Owner
  data:
    - secretKey: key
      remoteRef:
        key: iam_credentials/c4c5e90a-408d-69de-38b2-0d56d58d29db
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-infra-ssh-key
  namespace: test-pods
spec:
  refreshInterval: 60m
  secretStoreRef:
    name: secretstore-ibm-k8s
    kind: ClusterSecretStore
  target:
    name: k8s-infra-ssh-key
    creationPolicy: Owner
  data:
    - secretKey: ssh-privatekey
      remoteRef:
        key: 72d8039f-6cfc-1bbf-ba8e-d85985b42ee0
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: boskos-janitor-api-key
  namespace: test-pods
spec:
  refreshInterval: 60m
  secretStoreRef:
    name: secretstore-ibm-k8s
    kind: ClusterSecretStore
  target:
    name: boskos-janitor-api-key
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: iam_credentials/6db52764-fc6a-726f-b7b5-8f2e703793be
