instance-id: gateway-vm
local-hostname: gateway-vm
network:
  version: 2
  ethernets:
    nics:
      match:
        name: "e*"
      mtu: "1420"
      dhcp4: false
      addresses:
          - 192.168.32.8/21
      nameservers:
        addresses: [192.168.31.234]
      routes:
      - to: default
        via: 192.168.32.1
      - to: 192.168.31.234
        via: 192.168.32.1
