apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: atlantis

resources:
  - github.com/runatlantis/atlantis//kustomize
  - extras.yaml
  - httproute.yaml

images:
  - name: ghcr.io/runatlantis/atlantis
    newTag: v0.34.0

configMapGenerator:
  - name: atlantis-config
    files:
      - atlantis.yaml

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: atlantis
    spec:
      template:
        spec:
          serviceAccountName: atlantis
          containers:
          - name: atlantis
            env:
              - name: ATLANTIS_CONFIG
                value: /config/atlantis.yaml
              - name: ATLANTIS_GH_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: atlantis-vcs
                    key: token
              - name: ATLANTIS_GH_WEBHOOK_SECRET
                valueFrom:
                  secretKeyRef:
                    name: atlantis-vcs
                    key: webhook
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
              limits:
                cpu: 4
                memory: 6Gi
            volumeMounts:
            - name: config
              mountPath: /config
          volumes:
          - name: config
            configMap:
              name: atlantis-config
